### ISSUE TITLE
isSupported false on two recent devices

### ISSUE THREAD

**Issue by ghost** [mesmotronic/air-ane-immersivemode#1]
Hi, the two devices I've tried this ANE on, a nexus 5 w/ Android 6.0.1 and a Dell venue 8 (x86) with Android 5.1 both returned isSupported as false (as the stage is ready). I'm not sure if I do something wrong, I have no error at all... Gona try the other, AndroidFullscreen to see if I can get it to work. Sorry I cannot contribute to fix this as I know nothing about Java or ANEs...

**Comment by neilrackett** [comment]
The usual cause of this issue is that the ANE has been added to the library, but hasn't been included in the packaging options.

**Comment by ghost** [comment]
Thanks, I use flash pro, humm, Adobe Animate to compile, so it's added automatically in the app package when you add the ANE in the Library Path.  I might be an issue with the new Animate though. Will do more tests...

**Comment by ghost** [comment]
Ah! You were right!, my app.xml was read-only b/c of flash always screwing it up... Thanks again, It should work now, I guess ;)
